; SPDX-License-Identifier: AGPL-3.0-or-later
; Copyright (c) 2026 CommonHuman-Lab
; Author of this lab : roc1t1z3not <-> https://github.com/roc1t1z3not
[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:flask]
command=python /app/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:sshd]
command=/usr/sbin/sshd -D -e
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd.conf
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:telnetd]
command=/bin/busybox telnetd -F -l /bin/login -p 23
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null
