# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 CommonHuman-Lab
from ._types import LabDefinition

FIRERANGE_LABS: list[LabDefinition] = [  # type: ignore[assignment]
    {
        "id": 9,
        "slug": "breachsql",
        "name": "BreachSQL",
        "description": "57 SQL injection challenges across MySQL, PostgreSQL, and SQLite. Tiered T1–T5.",
        "category": "firerange",
        "container_names": [
            "octorig-breachsql-db",
            "octorig-breachsql-pg",
            "octorig-breachsql-app",
        ],
        "images": {
            "db": "mysql:8.0",
            "pg": "postgres:16-alpine",
            "app": "octorig-breachsql:latest",
        },
        "build_contexts": {"app": "labs/firerange"},
        "start_order": ["db", "pg", "app"],
        "exposed_ports": {"http": 80},
        "access_info": [
            {"key": "URL", "value": "http://{container_ip}"},
            {"key": "Challenges", "value": "GET /api/challenges"},
            {"key": "Submit flag", "value": "POST /api/submit-flag"},
            {"key": "Scoreboard", "value": "GET /scoreboard"},
        ],
        "volume_names": ["octorig-breachsql-scores"],
        "env_vars": {
            "MYSQL_HOST": "octorig-breachsql-db",
            "MYSQL_PORT": "3306",
            "MYSQL_USER": "firerange",
            "MYSQL_PASSWORD": "firerange",
            "MYSQL_DATABASE": "firerange",
            "PG_HOST": "octorig-breachsql-pg",
            "PG_PORT": "5432",
            "PG_USER": "firerange",
            "PG_PASSWORD": "firerange",
            "PG_DATABASE": "firerange",
        },
        "requires_privileged": False,
        "challenges": [],
    },
    {
        "id": 10,
        "slug": "stingxss",
        "name": "StingXSS",
        "description": "40+ XSS challenges: reflected, stored, DOM, blind, WAF bypass, CSP, GraphQL, WebSocket.",
        "category": "firerange",
        "container_names": ["octorig-stingxss"],
        "images": {"app": "octorig-stingxss:latest"},
        "build_contexts": {"app": "labs/stingxss"},
        "start_order": ["app"],
        "exposed_ports": {"http": 80},
        "access_info": [
            {"key": "URL", "value": "http://{container_ip}"},
            {"key": "Challenges", "value": "GET /api/challenges"},
            {"key": "Submit flag", "value": "POST /api/submit-flag"},
            {"key": "XSS beacon", "value": "GET /api/catch?cid=...&player=..."},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": False,
        "challenges": [],
    },
    {
        "id": 11,
        "slug": "vaultgate",
        "name": "VaultGate",
        "description": "IDOR / BOLA benchmarking: horizontal, obfuscated IDs, JWT tampering, mass assignment.",
        "category": "firerange",
        "container_names": ["octorig-vaultgate"],
        "images": {"app": "octorig-vaultgate:latest"},
        "build_contexts": {"app": "labs/vaultgate"},
        "start_order": ["app"],
        "exposed_ports": {"http": 80},
        "access_info": [
            {"key": "URL", "value": "http://{container_ip}"},
            {"key": "Challenges", "value": "GET /api/challenges"},
            {"key": "Submit flag", "value": "POST /api/submit-flag"},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": False,
        "challenges": [],
    },
    {
        "id": 12,
        "slug": "vaultriprange",
        "name": "VaultRip Range",
        "description": "Credential harvesting lab. SSH services with intentionally weak/exposed secrets.",
        "category": "firerange",
        "container_names": ["octorig-vaultriprange"],
        "images": {"app": "octorig-vaultriprange:latest"},
        "build_contexts": {"app": "labs/vaultriprange"},
        "start_order": ["app"],
        "exposed_ports": {"ssh": 22},
        "access_info": [
            {"key": "SSH", "value": "ssh admin@{container_ip}"},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": False,
        "challenges": [],
    },
]
