# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 CommonHuman-Lab
from ._types import LabDefinition

THIRDPARTY_LABS: list[LabDefinition] = [  # type: ignore[assignment]
    {
        "id": 13,
        "slug": "juiceshop",
        "name": "Juice Shop",
        "description": "OWASP Juice Shop — deliberately insecure Node.js web application.",
        "category": "thirdparty",
        "container_names": ["octorig-juiceshop"],
        "images": {"app": "bkimminich/juice-shop:latest"},
        "build_contexts": {},
        "start_order": ["app"],
        "network_name": "octorig-juiceshop-net",
        "subnet": "172.28.12.0/24",
        "app_ip": "172.28.12.2",
        "exposed_ports": {"http": 3000},
        "access_info": [
            {"key": "URL", "value": "http://172.28.12.2:3000"},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": False,
        "challenges": [],
    },
    {
        "id": 14,
        "slug": "dvwa",
        "name": "DVWA",
        "description": "Damn Vulnerable Web Application. Classic PHP/MySQL training target.",
        "category": "thirdparty",
        "container_names": ["octorig-dvwa"],
        "images": {"app": "ghcr.io/digininja/dvwa:latest"},
        "build_contexts": {},
        "start_order": ["app"],
        "network_name": "octorig-dvwa-net",
        "subnet": "172.28.13.0/24",
        "app_ip": "172.28.13.2",
        "exposed_ports": {"http": 80},
        "access_info": [
            {"key": "URL", "value": "http://172.28.13.2"},
            {"key": "Login", "value": "admin / password"},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": False,
        "challenges": [],
    },
    {
        "id": 15,
        "slug": "metasploitable",
        "name": "Metasploitable2",
        "description": "Classic intentionally vulnerable Linux VM in Docker form. Multi-service.",
        "category": "thirdparty",
        "container_names": ["octorig-metasploitable"],
        "images": {"app": "tleemcjr/metasploitable2:latest"},
        "build_contexts": {},
        "start_order": ["app"],
        "network_name": "octorig-metasploitable-net",
        "subnet": "172.28.14.0/24",
        "app_ip": "172.28.14.2",
        "exposed_ports": {"http": 80, "ftp": 21, "ssh": 22, "telnet": 23},
        "access_info": [
            {"key": "URL", "value": "http://172.28.14.2"},
            {"key": "SSH", "value": "ssh msfadmin@172.28.14.2 (password: msfadmin)"},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": True,
        "resource_limits": {"mem_limit": "1g", "memswap_limit": "1g", "cpu_quota": 100_000, "pids_limit": 512},
        "challenges": [],
    },
    {
        "id": 16,
        "slug": "webgoat",
        "name": "WebGoat",
        "description": "OWASP WebGoat — deliberately insecure Java web application for training.",
        "category": "thirdparty",
        "container_names": ["octorig-webgoat"],
        "images": {"app": "webgoat/webgoat:latest"},
        "build_contexts": {},
        "start_order": ["app"],
        "network_name": "octorig-webgoat-net",
        "subnet": "172.28.15.0/24",
        "app_ip": "172.28.15.2",
        "exposed_ports": {"http": 8080},
        "access_info": [
            {"key": "URL", "value": "http://172.28.15.2:8080/WebGoat"},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": False,
        "challenges": [],
    },
    {
        "id": 17,
        "slug": "vulnad",
        "name": "VulnAD",
        "description": "Vulnerable Active Directory environment. Samba4 DC with misconfigured GPOs.",
        "category": "thirdparty",
        "container_names": ["octorig-vulnad"],
        "images": {"app": "octorig-vulnad:latest"},
        "build_contexts": {"app": "labs/vulnad"},
        "start_order": ["app"],
        "network_name": "octorig-vulnad-net",
        "subnet": "172.28.17.0/24",
        "app_ip": "172.28.17.2",
        "exposed_ports": {"ldap": 389, "smb": 445, "kerberos": 88},
        "access_info": [
            {"key": "Domain", "value": "VULNAD.LOCAL"},
            {"key": "DC IP", "value": "172.28.17.2"},
            {"key": "Admin", "value": "Administrator / Passw0rd!"},
        ],
        "volume_names": [],
        "env_vars": {},
        "requires_privileged": True,
        # Samba4 AD DC (built from source) needs significant memory and CPU headroom
        "resource_limits": {"mem_limit": "2g", "memswap_limit": "2g", "cpu_quota": 100_000, "pids_limit": 512},
        "challenges": [],
    },
]
