version: "3.9"

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.8.2
    hostname: wazuh.manager
    container_name: wazuh.manager

    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"

    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword

    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue

    networks:
      - octorig-net

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.8.2
    hostname: wazuh.indexer
    container_name: wazuh.indexer

    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g

    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"

    networks:
      - octorig-net

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.8.2
    hostname: wazuh.dashboard
    container_name: wazuh.dashboard

    ports:
      - "5601:5601"

    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager

    networks:
      - octorig-net

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:

networks:
  octorig-net:
    external: true