from app.models.badge import AchievementRuleType

COMPETITION_BADGES = [
    {
        "slug": "first-blood",
        "name": "Bloodhound",
        "description": "Achieved first blood on any challenge.",
        "icon": "droplets",
        "category": "competition",
        "points_value": 100,
        "rule_type": AchievementRuleType.FIRST_BLOOD,
        "rule_config": {},
    },
    {
        "slug": "triple-blood",
        "name": "Serial Bleeder",
        "description": "Achieved first blood on 3 different challenges.",
        "icon": "siren",
        "category": "competition",
        "points_value": 200,
        "rule_type": AchievementRuleType.FIRST_BLOOD,
        "rule_config": {"threshold": 3},
    },
    {
        "slug": "five-bloods",
        "name": "Knife's Edge",
        "description": "Achieved first blood on 5 different challenges.",
        "icon": "sword",
        "category": "competition",
        "points_value": 300,
        "rule_type": AchievementRuleType.FIRST_BLOOD,
        "rule_config": {"threshold": 5},
    },
    {
        "slug": "ten-bloods",
        "name": "Bloodbath",
        "description": "Achieved first blood on 10 different challenges.",
        "icon": "skull",
        "category": "competition",
        "points_value": 500,
        "rule_type": AchievementRuleType.FIRST_BLOOD,
        "rule_config": {"threshold": 10},
    },
    {
        "slug": "twenty-bloods",
        "name": "Apex Predator",
        "description": "Achieved first blood on 20 different challenges.",
        "icon": "flame",
        "category": "competition",
        "points_value": 750,
        "rule_type": AchievementRuleType.FIRST_BLOOD,
        "rule_config": {"threshold": 20},
    },
    {
        "slug": "fifty-bloods",
        "name": "Crimson Ghost",
        "description": "Achieved first blood on 50 different challenges.",
        "icon": "ghost",
        "category": "competition",
        "points_value": 1500,
        "rule_type": AchievementRuleType.FIRST_BLOOD,
        "rule_config": {"threshold": 50},
    },
]
