from app.models.badge import AchievementRuleType

MILESTONE_BADGES = [
    {
        "slug": "first-steps",
        "name": "First Steps",
        "description": "Solved your first challenge.",
        "icon": "flag",
        "category": "milestone",
        "points_value": 0,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 1},
    },
    {
        "slug": "two-solves",
        "name": "Double Down",
        "description": "Solved 2 challenges.",
        "icon": "flag",
        "category": "milestone",
        "points_value": 0,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 2},
    },
    {
        "slug": "three-solves",
        "name": "Hat Trick",
        "description": "Solved 3 challenges.",
        "icon": "layers",
        "category": "milestone",
        "points_value": 0,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 3},
    },
    {
        "slug": "five-solves",
        "name": "Getting Started",
        "description": "Solved 5 challenges.",
        "icon": "star",
        "category": "milestone",
        "points_value": 0,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 5},
    },
    {
        "slug": "seven-solves",
        "name": "Lucky Seven",
        "description": "Solved 7 challenges.",
        "icon": "dice-4",
        "category": "milestone",
        "points_value": 0,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 7},
    },
    {
        "slug": "ten-solves",
        "name": "Ten Solver",
        "description": "Solved 10 challenges.",
        "icon": "hash",
        "category": "milestone",
        "points_value": 50,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 10},
    },
    {
        "slug": "fifteen-solves",
        "name": "On the Board",
        "description": "Solved 15 challenges.",
        "icon": "bar-chart-2",
        "category": "milestone",
        "points_value": 25,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 15},
    },
    {
        "slug": "twenty-five-solves",
        "name": "On a Roll",
        "description": "Solved 25 challenges.",
        "icon": "target",
        "category": "milestone",
        "points_value": 75,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 25},
    },
    {
        "slug": "thirty-solves",
        "name": "Committed",
        "description": "Solved 30 challenges.",
        "icon": "activity",
        "category": "milestone",
        "points_value": 50,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 30},
    },
    {
        "slug": "fifty-solves",
        "name": "Grinder",
        "description": "Solved 50 challenges.",
        "icon": "zap",
        "category": "milestone",
        "points_value": 200,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 50},
    },
    {
        "slug": "seventy-five-solves",
        "name": "The Long Game",
        "description": "Solved 75 challenges.",
        "icon": "trending-up",
        "category": "milestone",
        "points_value": 150,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 75},
    },
    {
        "slug": "hundred-solves",
        "name": "Centurion",
        "description": "Solved 100 challenges.",
        "icon": "trophy",
        "category": "milestone",
        "points_value": 1000,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 100},
    },
    {
        "slug": "two-hundred-solves",
        "name": "Machine",
        "description": "Solved 200 challenges.",
        "icon": "cpu",
        "category": "milestone",
        "points_value": 2000,
        "rule_type": AchievementRuleType.SOLVE_COUNT,
        "rule_config": {"threshold": 200},
    },
]
